INPUT_DIRECTORYNAME = "data"
INPUT_IMAGES_DIRECTORYNAME = "input"
INPUT_MOVIE_FILENAME = "input.mp4"

OUTPUT_DIRECTORYNAME = "results"
OUTPUT_IMAGES_DIRECTORYNAME = "output_images"
OUTPUT_MOVIE_FILENAME = "output.mp4"
OUTPUT_AUDIO_FILENAME = "output_audio.mp3"

PRETRAINED_MODELS_DIRECTORY = "pretrained_models"
